<?php
/**
 * 分类管理
 *
 * @author     chenfenghua<843958575@qq.com>
 * @copyright  Copyright 2014-2016
 * @version    2.0
 */

namespace app\app\backend\modules\zb\controllers;

use app\models\common\UploadFile;
use app\models\zb\ZbContent;
use Yii;
use app\app\backend\components\BaseController;
use app\app\backend\modules\zb\components\Search;
use app\models\zb\ZbCat;
use yii\data\Pagination;
use yii\db\Query;
use yii\helpers\Json;

class CatController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->data['css']  = [
            'global/plugins/bootstrap-fileinput/bootstrap-fileinput.css',
            'global/plugins/fancybox/source/jquery.fancybox.css',
            'global/plugins/bootstrap-switch/css/bootstrap-switch.min.css',
        ];
        $this->data['js']   = [
            'global/plugins/bootstrap-fileinput/bootstrap-fileinput.js',
            'global/plugins/fancybox/source/jquery.fancybox.pack.js',
            'global/plugins/bootstrap-switch/js/bootstrap-switch.min.js',
            'backend/zb/cat.js'
        ];
    }

    /**
     * 列表
     */
    public function actionIndex()
    {
        $pageIndex = Yii::$app->request->get('page', 1);
        $this->data['search_attributes'] = Yii::$app->request->get();

        $query = new Query();
        $model = $query->from(ZbCat::tableName().' t')->where(['t.disabled'=>'false']);

        if ($this->data['search_attributes']) {
            $model = Search::cat($this->data['search_attributes'], $model);
        }
        $this->data['count'] = $model->count();
        $this->data['dataProvider'] = $model->select(['t.*'])
            ->orderBy(['t.p_order'=>SORT_ASC, 't.cat_id'=>SORT_DESC])
            ->offset(($pageIndex - 1) * $this->pageSize)->limit($this->pageSize)->all();

        $this->data['pages'] = new Pagination(
            [
                'totalCount' => $this->data['count'],
                'defaultPageSize'=>$pageIndex,
                'pageSizeLimit'=>[$this->pageSize,$this->pageSize]
            ]
        );

        return $this->render('index', $this->data);
    }

    /**
     * 创建
     */
    public function actionCreate()
    {
        $attributes = Yii::$app->request->post('Cat');
        if ($attributes)
        {
            $attributes['create_time'] = time();
            $attributes['creator'] = Yii::$app->session['user_id'];

            $file_attributes = Yii::$app->request->post('File');
            if ($file_attributes['logo']) $attributes['cat_img'] = UploadFile::common($file_attributes['logo'], 'zb_cat', false);

            $cat = new ZbCat();
            $cat->attributes = $attributes;
            $submit = $cat->save()?200:500;
            if ($submit == 200) $this->redirect('?r=zb/cat/index');
            else $this->refresh('&ref_sub='.$submit);
        }
        $this->data['action'] = 'create';
        return $this->render('create', $this->data);
    }

    /**
     * 编辑
     */
    public function actionUpdate()
    {
        $cat_id = Yii::$app->request->get('cat_id');

        $attributes = Yii::$app->request->post('Cat');
        if ($attributes) {
            $attributes['update_time'] = time();
            $attributes['updater'] = Yii::$app->session['user_id'];

            $file_attributes = Yii::$app->request->post('File');
            if ($file_attributes['logo']) $attributes['cat_img'] = UploadFile::common($file_attributes['logo'], 'zb_cat', false);

            $cat = new ZbCat();
            $cat->attributes = $attributes;
            $submit = $cat->updateAll($attributes, 'cat_id = :cat_id', [':cat_id'=>$cat_id])?200:500;
            $this->refresh('&ref_sub='.$submit);;
        }
        $this->data['cat_row'] = ZbCat::findOne(['cat_id'=>$cat_id]);
        $this->data['action'] = 'update&cat_id='.$cat_id;
        return $this->render('create', $this->data);
    }

    /**
     * 删除
     */
    public function actionDelete()
    {
        $cat_id = Yii::$app->request->get('cat_id');
        if (!$cat_id) return Json::encode(['code'=>500, 'msg'=>'没有获取请求的ID']);
        if (ZbContent::find()->select('content_id')->where(['cat_id'=>$cat_id])->count())
            return Json::encode(['code'=>500, 'msg'=>'当然分类存在素材不可删除']);

        $attributes['disabled'] = 'true';
        $attributes['update_time'] = time();
        $attributes['updater'] = Yii::$app->session['user_id'];
        $submit = ZbCat::updateAll($attributes, 'cat_id = :cat_id', [':cat_id'=>$cat_id])?200:500;
        if ($submit == 500) return Json::encode(['code'=>500, 'msg'=>'删除失败']);
        return Json::encode(['code'=>200]);
    }
}