<?php
/**
 * 后台管理员管理
 *
 * @author     chenfenghua<843958575@qq.com>
 * @copyright  Copyright 2014-2016
 * @version    2.0
 */

namespace app\admin\controller;

use app\admin\model\AdminGroup;
use app\admin\model\AdminRole;
use app\admin\model\AdminUser;
use app\common\components\AppAdminAcl;
use think\Controller;
use app\admin\components\Search;
use think\facade\Session;
use think\Request;


class Admin extends Controller
{
    private $data = [];
    public $pageSize = 10;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $aclList = AppAdminAcl::filterMenu(Session::get("acl"), Session::get("super"));
        $this->data['aclList'] = $aclList;
    }


    /**
     * 列表页
     */
    public function index(Request $req)
    {
        $this->data['title'] = '管理员管理';
        $this->data['breadcrumbs'] = [['label'=>'管理员和权限','url'=>'?r=admin/admin/index'],['label'=>'管理员管理']];

        $this->data['search_attributes'] = $search = $req->param();

        $data = AdminUser::where('status', '=', 0);
        if ($search) {
            $data = Search::admin($search, $data);
        }
        $list = $data->order('user_id DESC')->paginate($this->pageSize);
        $page = $list->render();
        $this->data['list'] = $list;
        $this->data['page'] = $page;

        return $this->fetch('index', $this->data);
    }

    /**
     * 创建
     */
    public function actionCreate()
    {
        if (Yii::$app->request->post())
        {
            $user_attributes = Yii::$app->request->post('User');
            $user_attributes['password'] = md5(md5($user_attributes['password']));
            $user_attributes['last_modify'] = time();

            $role_attributes = Yii::$app->request->post('Role');

            $adminUser = new AdminUser();
            $adminRole = new AdminRole();
            $adminUser->attributes = $user_attributes;
            $submit = $adminUser->save()?200:500;
            $role_attributes['user_id'] = Yii::$app->db->getLastInsertID();

            if ($submit == 200) {
                $adminRole->attributes = $role_attributes;
                $adminRole->save();
            }
            $this->refresh('&ref_sub='.$submit);
        }
        $this->data['action'] = 'create';
        $this->data['role_list'] = AdminGroup::findAll(['status'=>'active']);
        return $this->render('create', $this->data);
    }

    /**
     * 编辑
     */
    public function actionUpdate()
    {
        $user_id = Yii::$app->request->get('user_id');
        if (Yii::$app->request->post())
        {
            $user_attributes = Yii::$app->request->post('User');

            $user_attributes['last_modify'] = time();

            $role_attributes = Yii::$app->request->post('Role');

            $adminUser = AdminUser::findOne($user_id);
            if ($user_attributes['password']) $user_attributes['password'] = md5(md5($user_attributes['password']));
            else $user_attributes['password'] = $adminUser->password;
            $adminRole = AdminRole::findOne($user_id);
            $adminUser->attributes = $user_attributes;

            $submit = $adminUser->update()?200:500;
            if ($submit == 200) {
                if ($adminRole) {
                    $adminRole->attributes = $role_attributes;
                    $adminRole->update();
                } else {
                    $adminRole = new AdminRole();
                    $role_attributes['user_id'] = $user_id;
                    $adminRole->attributes = $role_attributes;
                    $adminRole->save();
                }
            }
            $this->refresh('&ref_sub='.$submit);
        }
        $this->data['action'] = 'update&user_id='.$user_id;
        $this->data['user_row'] = AdminUser::findOne(['user_id'=>$user_id]);
        $this->data['role_row'] = AdminRole::findOne(['user_id'=>$user_id]);
        $this->data['role_list'] = AdminGroup::findAll(['status'=>'active']);

        return $this->render('update', $this->data);
    }

    /**
     * 取消
     */
    public function actionCancel()
    {
        $user_id = Yii::$app->request->get('user_id');
        if (!$user_id) return Json::encode(['code'=>500, 'msg'=>'没有获取请求的ID']);
        $submit = AdminUser::updateAll(['status'=>'1'], 'user_id = :user_id', [':user_id'=>$user_id])?200:500;
        if ($submit == 500) return Json::encode(['code'=>500, 'msg'=>'冻结失败']);
        return Json::encode(['code'=>200]);
    }
}