<?php
/**
 * 角色管理
 *
 * @author     chenfenghua<843958575@qq.com>
 * @copyright  Copyright 2014-2016
 * @version    2.0
 */

namespace app\admin\controller;

use think\Controller;
use app\admin\model\AdminGroup;
use app\common\components\AppAdminAcl;
use think\Request;
use think\facade\Session;


class Role extends Controller
{
    private $data = [];
    public $pageSize = 10;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $aclList = AppAdminAcl::filterMenu(Session::get("acl"), Session::get("super"));
        $this->data['aclList'] = $aclList;
    }

    /**
     * 角色列表
     */
    public function index()
    {
//        $pageIndex = $req->get('page', 1);

//        $this->data['count'] = AdminGroup::where('status', 'active')->count();
//        $this->data['dataProvider'] = AdminGroup::where('status', 'active')->order('role_id ' . SORT_ASC)->page($pageIndex, $this->pageSize)->select();
//
//        $this->data['pages'] = new Pagination(
//            [
//                'totalCount' => $this->data['count'],
//                'defaultPageSize'=>$pageIndex,
//                'pageSizeLimit'=>[$this->pageSize,$this->pageSize]
//            ]
//        );

        $this->data['title'] = '角色管理';
        $this->data['breadcrumbs'] = [['label'=>'管理员和权限','url'=>'/admin/role/index'],['label'=>'角色管理']];

        $list = AdminGroup::where('status', 'active')->order('role_id ' . SORT_ASC)->paginate($this->pageSize);
        $page = $list->render();
        $this->data['list'] = $list;
        $this->data['page'] = $page;

        return $this->fetch('index', $this->data);
    }

    /**
     * 创建
     */
    public function create(Request $req)
    {
        $this->data['title'] = '角色管理';
        $this->data['breadcrumbs'] = [['label'=>'管理员和权限','url'=>'/admin/role/index'],['label'=>'角色管理','url'=>'/admin/role/index'],['label'=>'添加']];

        if ($req->post())
        {
            $group_attributes = $req->post('Group');
            $group_attributes['last_modify'] = time();
            $acl_attributes = $req->post('Acl');

            if ($acl_attributes) $group_attributes['acl'] = implode(',', $acl_attributes);
            $adminGroup = new AdminGroup();
//            $adminGroup->attributes = $group_attributes;
            $submit = $adminGroup->save($group_attributes)?200:500;
//            $this->refresh('&ref_sub='.$submit);
            $this->redirect('create', ['ref_sub' => $submit]);
        }
        $this->data['action'] = 'create';
        return $this->fetch('create', $this->data);
    }

    /**
     * 编辑
     */
    public function update(Request $req)
    {
        $role_id = Yii::$app->request->get('role_id');
        if (Yii::$app->request->post())
        {
            $group_attributes = Yii::$app->request->post('Group');
            $group_attributes['last_modify'] = time();
            $acl_attributes = Yii::$app->request->post('Acl');

            if ($acl_attributes) $group_attributes['acl'] = implode(',', $acl_attributes);
            $adminGroup = AdminGroup::findOne($role_id);
            $adminGroup->attributes = $group_attributes;
            $submit = $adminGroup->update()?200:500;
            $this->refresh('&ref_sub='.$submit);
        }
        $this->data['action'] = 'update&role_id='.$role_id;
        $this->data['role_row'] = AdminGroup::find()->where(['role_id'=>$role_id])->one();
        return $this->fetch('update', $this->data);
    }

    /**
     * 冻结
     */
    public function cancel(Request $req)
    {
        $this->enableCsrfValidation = false;
        $role_id = Yii::$app->request->get('role_id');
        if (!$role_id) return Json::encode(['code'=>500, 'msg'=>'没有获取请求的ID']);
        $submit = AdminGroup::updateAll(['status'=>'dead'], 'role_id = :role_id', [':role_id'=>$role_id])?200:500;
        if ($submit == 500) return Json::encode(['code'=>500, 'msg'=>'冻结失败']);
        return Json::encode(['code'=>200]);
    }
}