<?php
/**
 * 角色管理
 *
 * @author     chenfenghua<843958575@qq.com>
 * @copyright  Copyright 2014-2016
 * @version    2.0
 */

namespace app\admin\controller;

use think\Controller;
use app\admin\model\AdminGroup;
use app\common\components\AppAdminAcl;
use think\Request;
use think\facade\Session;


class Role extends Controller
{
    private $data = [];
    public $pageSize = 10;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $aclList = AppAdminAcl::filterMenu(Session::get("acl"), Session::get("super"));
        $this->data['aclList'] = $aclList;
    }

    /**
     * 角色列表
     */
    public function index()
    {
        $this->data['title'] = '角色管理';
        $this->data['breadcrumbs'] = [['label'=>'管理员和权限','url'=>'/admin/role/index'],['label'=>'角色管理']];

        $list = AdminGroup::where('status', 'active')->order('role_id ' . SORT_ASC)->paginate($this->pageSize);
        $page = $list->render();
        $this->data['list'] = $list;
        $this->data['page'] = $page;

        return $this->fetch('index', $this->data);
    }

    /**
     * 创建
     */
    public function create(Request $req)
    {
        $this->data['title'] = '角色管理';
        $this->data['breadcrumbs'] = [['label'=>'管理员和权限','url'=>'/admin/role/index'],['label'=>'角色管理','url'=>'/admin/role/index'],['label'=>'添加']];

        if ($req->post())
        {
            $attributes = $req->param();
            $group = $attributes['Group'];
            $group['last_modify'] = time();
            $acl = $attributes['Acl'];

            if ($acl) $group['acl'] = implode(',', $acl);
            $adminGroup = new AdminGroup();
            $submit = $adminGroup->save($group)?200:500;
//            $this->refresh('&ref_sub='.$submit);
            $this->redirect('create', ['ref_sub' => $submit]);
        }
        $this->data['action'] = 'create';
        return $this->fetch('create', $this->data);
    }

    /**
     * 编辑
     */
    public function update(Request $req)
    {

        $this->data['title'] = '角色管理';
        $this->data['breadcrumbs'] = [['label'=>'管理员和权限','url'=>'?r=admin/role/index'],['label'=>'角色管理','url'=>'?r=admin/role/index'],['label'=>'编辑']];

        $role_id = $req->param('role_id');
        if ($req->post())
        {
            $attributes = $req->param();
            $group = $attributes['Group'];
            $group['last_modify'] = time();
            $acl = $attributes['Acl'];

            if ($acl) $group['acl'] = implode(',', $acl);
            $adminGroup = new AdminGroup();
            $submit = $adminGroup->save($group, ['role_id' => $role_id]) ? 200 : 500;
            $this->redirect('update', ['role_id' => $role_id, 'ref_sub' => $submit]);
        }
        $this->data['action'] = 'update/role_id/'.$role_id;
        $this->data['role_row'] = AdminGroup::where(['role_id'=>$role_id])->find();
        return $this->fetch('update', $this->data);
    }

    /**
     * 冻结
     */
    public function cancel(Request $req)
    {
//        $this->enableCsrfValidation = false;
        $role_id = $req->param('role_id');
        if (!$role_id) return json(['code'=>500, 'msg'=>'没有获取请求的ID']);
        $adminGroup = new AdminGroup();
        $submit = $adminGroup->save(['status'=>'dead'], ['role_id'=>$role_id])?200:500;
        if ($submit == 500) return json(['code'=>500, 'msg'=>'冻结失败']);
        return json(['code'=>200]);
    }
}