<?php
namespace app\common\controller;

use app\common\components\AppAdminAcl;
use think\Controller;
use think\facade\Session;

class BaseController extends Controller {

    protected $data = [];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        if(empty(Session::get("user_id"))) {
            $this->redirect("/admin/user/login");
        }

        $aclList = AppAdminAcl::filterMenu(Session::get("acl"), Session::get("super"));
        $this->data['aclList'] = $aclList;
    }
}
?>