<?php
/**
 * 缓存管理
 *
 * @author     chenfenghua<843958575@qq.com>
 * @copyright  Copyright 2014-2016
 * @version    2.0
 */

namespace app\app\backend\modules\zb\controllers;

use Yii;
use app\app\backend\components\BaseController;

class CacheController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        Yii::$app->cache->flush();
        return $this->render('index');
    }
}