<?php
/**
 * 素材管理
 *
 * @author     chenfenghua<843958575@qq.com>
 * @copyright  Copyright 2014-2016
 * @version    2.0
 */

namespace app\app\backend\modules\zb\controllers;

use app\models\zb\ZbCat;
use Yii;
use app\app\backend\components\BaseController;
use app\app\backend\modules\zb\components\Search;
use app\models\common\UploadFile;
use app\models\zb\ZbContent;
use yii\data\Pagination;
use yii\db\Query;
use yii\helpers\Json;

class ContentController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->data['css']  = [
            'global/plugins/bootstrap-fileinput/bootstrap-fileinput.css',
            'global/plugins/fancybox/source/jquery.fancybox.css',
            'global/plugins/bootstrap-switch/css/bootstrap-switch.min.css',
        ];
        $this->data['js']   = [
            'global/plugins/bootstrap-fileinput/bootstrap-fileinput.js',
            'global/plugins/fancybox/source/jquery.fancybox.pack.js',
            'global/plugins/bootstrap-switch/js/bootstrap-switch.min.js',
            'backend/zb/content.js'
        ];
    }

    /**
     * 列表
     */
    public function actionIndex()
    {
        $pageIndex = Yii::$app->request->get('page', 1);
        $this->data['search_attributes'] = Yii::$app->request->get();

        $query = new Query();
        $model = $query->from(ZbContent::tableName().' t')->where(['t.disabled'=>'false']);

        if ($this->data['search_attributes']) {
            $model = Search::content($this->data['search_attributes'], $model);
        }
        $model = $model->leftJoin(ZbCat::tableName().'t2', 't.cat_id = t2.cat_id');
        $this->data['count'] = $model->count();
        $this->data['dataProvider'] = $model->select(['t.*','t2.cat_name'])
            ->orderBy(['t.p_order'=>SORT_ASC, 't.content_id'=>SORT_DESC])
            ->offset(($pageIndex - 1) * $this->pageSize)->limit($this->pageSize)->all();

        $this->data['pages'] = new Pagination(
            [
                'totalCount' => $this->data['count'],
                'defaultPageSize'=>$pageIndex,
                'pageSizeLimit'=>[$this->pageSize,$this->pageSize],
            ]
        );

        return $this->render('index', $this->data);
    }

    /**
     * 创建
     */
    public function actionCreate()
    {
        $attributes = Yii::$app->request->post('Content');
        if ($attributes)
        {
            $attributes['create_time'] = time();
            $attributes['creator'] = Yii::$app->session['user_id'];

            $file_attributes = Yii::$app->request->post('File');
            if ($file_attributes['img_icon']) $attributes['img_icon'] = UploadFile::common($file_attributes['img_icon'], 'zb_content', false);
            if ($file_attributes['img_example']) $attributes['img_example'] = UploadFile::common($file_attributes['img_example'], 'zb_content', false);

            $content = new ZbContent();
            $content->attributes = $attributes;
            $submit = $content->save()?200:500;
            if ($submit == 200) $this->redirect('?r=zb/content/index');
            else $this->refresh('&ref_sub='.$submit);
        }
        $this->data['action'] = 'create';
        $this->data['cat_list'] = ZbCat::findAll(['disabled'=>'false']);
        return $this->render('create', $this->data);
    }

    /**
     * 编辑
     */
    public function actionUpdate()
    {
        $content_id = Yii::$app->request->get('content_id');

        $attributes = Yii::$app->request->post('Content');
        if ($attributes) {
            $attributes['update_time'] = time();
            $attributes['updater'] = Yii::$app->session['user_id'];

            $file_attributes = Yii::$app->request->post('File');
            if ($file_attributes['img_icon']) $attributes['img_icon'] = UploadFile::common($file_attributes['img_icon'], 'zb_content', false);
            if ($file_attributes['img_example']) $attributes['img_example'] = UploadFile::common($file_attributes['img_example'], 'zb_content', false);

            $content = new ZbContent();
            $content->attributes = $attributes;
            $submit = $content->updateAll($attributes, 'content_id = :content_id', [':content_id'=>$content_id])?200:500;
            $this->refresh('&ref_sub='.$submit);;
        }
        $this->data['content_row'] = ZbContent::findOne(['content_id'=>$content_id]);
        $this->data['cat_list'] = ZbCat::findAll(['disabled'=>'false']);
        $this->data['action'] = 'update&content_id='.$content_id;
        return $this->render('update', $this->data);
    }

    /**
     * 删除
     */
    public function actionDelete()
    {
        $content_id = Yii::$app->request->get('content_id');
        if (!$content_id) return Json::encode(['code'=>500, 'msg'=>'没有获取请求的ID']);
        $attributes['disabled'] = 'true';
        $attributes['update_time'] = time();
        $attributes['updater'] = Yii::$app->session['user_id'];
        $submit = ZbContent::updateAll($attributes, 'content_id = :content_id', [':content_id'=>$content_id])?200:500;
        if ($submit == 500) return Json::encode(['code'=>500, 'msg'=>'删除失败']);
        return Json::encode(['code'=>200]);
    }

    public function actionCache()
    {
        Yii::$app->cache->flush();
    }
}